### ISSUE TITLE
Error while processing indic voice

### ISSUE THREAD

**Issue by MaheshVelankar** [pbaljeka/world_merlin#2]
I am trying to run this recipe for indic marathi voice.

I am getting this error:

2018-02-19 18:26:34,860 INFO           main    : normalising acoustic (output) features using method MVN
Traceback (most recent call last):
  File "ss_dnn/merlin_scripts/src/run_dnn.py", line 983, in <module>
    main_function(cfg)
  File "ss_dnn/merlin_scripts/src/run_dnn.py", line 691, in main_function
    nn_cmp_norm_file_list[0:int(cfg.train_file_number)+int(cfg.valid_file_number)])
  File "/mnt/disks/disk1/gits/cmu_indic_mar_msv/ss_dnn/merlin_scripts/src/frontend/mean_variance_norm.py", line 69, in feature_normalisation
    if self.mean_vector == None:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

....
please let me know what more details I should provide
Thanks

**Comment by skmalviya** [comment]
I am getting the same error too on Hindi CMU dataset, is there anything missing to set in the conf file as nothing is mentioned in the readme regarding the size of the dataset.

THank you!!
